### ISSUE TITLE
so $MYVIMRC breaks 

### ISSUE THREAD

**Issue by mohitleo9** [bling/dotvim#15]
Hey 
Whenever I try to do a so $MYVIMRC it just breaks the color scheme and also for some reason it thinks that the buffer has changed even though it hasn't 
I have wrapped all the autocommands in augroups with au! .
Also I have tried disabling all the plugins the problem still remains

**Comment by BjornMelgaard** [comment]
I have an error when I do `so $MYVIMRC`

```
Error detected while processing /home/bjorn/.config/dotfiles/nvim/vimrc:                                                              
line  524:                                                                                                                            
E122: Function <SNR>2_on_unite_source already exists, add ! to replace it     
```

On line 524 written end of `function s:on_unite_source()`
