### ISSUE TITLE
Installation Error: Segmentation fault: 11

### ISSUE THREAD

**Issue by adrianmarino** [bling/dotvim#23]
Hello, I have an error after run "cd .vim; make install", just after download all neobundle packages (On OSX Yosemite 10.10.5,  xcode Version 6.4 (6E35b) ):

```
vim -u bundles.vim +NeoBundleClean +NeoBundleCheck +NeoBundleDocs
Vim: Caught deadly signal SEGV
Vim: Finished.
make: *** [cleanup] Segmentation fault: 11
```
Any idea?

Thanks.

**Comment by bling** [comment]
neobundle has been replaced with dein
