### ISSUE TITLE
Getting weird character for strings on JSON files

### ISSUE THREAD

**Issue by jfalameda** [bling/dotvim#32]
Hi,

I am having issues with JSON files. The quotes are displayed as triangles. I attach a picture of the problem. I have verified that this is not caused by my typography. Using iterm2 on mac.

Thanks in advance.

![screen shot 2016-06-03 at 12 46 14](https://cloud.githubusercontent.com/assets/287670/15776631/69471edc-2989-11e6-90a8-2c310c67e45d.png)

**Comment by skrat** [comment]
Same here. Weird default.

![JSON](http://i.imgur.com/TGtz0Mm.png)
